import type { MetadataRoute } from "next";

// Web app manifest — lets mobile users add Mind Video to the homescreen with
// the brand mark and Mind Green chrome. Maskable icons (generated by
// scripts/gen-icons.mjs from the canonical mark) bleed green to the edges so the
// platform mask can crop the corners without clipping the weave.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Mind Video — reels from your pod",
    short_name: "Videos",
    description:
      "Drop photos and videos, let Mind caption them, then describe the reel you want. The agent plans a ReelSpec that previews in your browser and renders to an MP4 in your pod — never our servers.",
    start_url: "/",
    display: "standalone",
    background_color: "#07080b",
    theme_color: "#16B88A",
    // Both PNGs live in public/ (served at the root) and carry the green to the
    // edges; the 512 doubles as the "any" icon (a little safe-zone padding is
    // fine there). Separate entries per purpose — Next's manifest type rejects
    // the space-separated "any maskable" form the spec allows.
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
